FROM daprio/daprd
RUN 
# RUN  apt-get update \
#   && apt-get install -y wget \
#   && rm -rf /var/lib/apt/lists/*

# Install dapr CLI
# RUN wget -q https://raw.githubusercontent.com/dapr/cli/master/install/install.sh -O - | /bin/bash

# # Install daprd
# ARG DAPR_BUILD_DIR
# COPY $DAPR_BUILD_DIR /opt/dapr
# ENV PATH="/opt/dapr/:${PATH}"

# # Install your app
# # WORKDIR /app
# # COPY python .
# # RUN pip install requests
# ENTRYPOINT ["dapr"]
# CMD ["run", "--app-id", "nodeapp",\
#     "--app-port", "3000",\
#     "--dapr-grpc-port", "50001",\
#     "--dapr-http-port", "3502",\
#     "--placement-host-address", "placement:50006",\
#     "--resources-path", "./components"]
