openapi: 3.1.0
info:
  title: Fin2Set API
  description: Public operations exposed by Fin2Set
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /api/chat_initial_message:
    get:
      summary: Initial message from Assistant if it may initiate the discussion
      description: Creates initial message of AI, based on what the AI is capable to offer. Better replacemend of *Hello, I am CHat GPT, how can I help you today?*
      tags:
        - Chat
      operationId: welcomeMessage
      responses:
        '200':
          description: Welcome message
          content:
            application/json:
              schema:
                type: TextDTO

components:
  schemas:

    # Instead of returning simple text/plain I use TextDTO as
    # using string as returned value I had issue with java tests and javascript client
    # TODO refactor remove and replace with plain/text
    TextDTO:
      type: object
      required: [value]
      properties:
        value:
          type: string 
