apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: fin2set
spec:
  type: secretstores.local.env
  version: v1
  metadata:
    - name: prefix
      value: FIN2SET_

# expected variables:
# http://localhost:3601/v1.0/secrets/fin2set/CLIENT_ID as FIN2SET_CLIENT_ID should be available
# http://localhost:3601/v1.0/secrets/fin2set/CLIENT_SECRET as FIN2SET_CLIENT_SECRET should be available
