apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: azurekeyvault
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
  - name: vaultName
    value: fin2set-magnetic-gator
  - name: azureTenantId
    secretKeyRef:
      name: TENANT_ID
      value: TENANT_ID
  - name: azureClientId
    secretKeyRef:
      name: APP_ID
      value: APP_ID
  - name: azureClientSecret
    secretKeyRef:
      name: APP_SECRET
      value: APP_SECRET
  - name: azureCertificateFile
    value : "/.secrets/service-principal.pem"
auth:
  secretStore: fin2set

