apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: azurekeyvault
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
  - name: vaultName
    value: fin2set-magnetic-gator
  - name: azureTenantId
    value: 29084a59-db89-4eb9-908a-53f42318c77d
  - name: azureClientId
    secretKeyRef:
      name: CLIENT_ID
      value: CLIENT_ID
  - name: azureClientSecret
    secretKeyRef:
      name: CLIENT_SECRET
      value: CLIENT_SECRET

auth:
  secretStore: fin2set

