apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: localsecretstore
spec:
  type: secretstores.local.file
  version: v1
  metadata:
  - name: secretsFile
    # The path to the secret store JSON is relative to where you call dapr run
    value: components/.local/dapr-local-secrets.json
  - name: nestedSeparator
    value: ":"
