/*
 * Nordigen Account Information Services API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0 (v2)
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package nordigen;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.time.OffsetDateTime;
import java.util.Objects;
import java.util.UUID;

/**
 * AccountV2Serializer.
 */@ApiModel(description = "AccountV2Serializer.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2023-02-25T17:56:18.166387600+01:00[Europe/Warsaw]")
public class AccountV2 {

  
  @JsonProperty("id")
  private UUID id = null;
  
  
  @JsonProperty("created")
  private OffsetDateTime created = null;
  
  
  @JsonProperty("last_accessed")
  private OffsetDateTime lastAccessed = null;
  
  
  @JsonProperty("iban")
  private String iban = null;
  
  
  @JsonProperty("institution_id")
  private String institutionId = null;
  
  
  @JsonProperty("status")
  private Object status = null;
  
  
  @JsonProperty("owner_name")
  private String ownerName = null;
  
  
  /**
  * The ID of this Account, used to refer to this account in other API calls.
  * @return id
  **/
  @ApiModelProperty(value = "The ID of this Account, used to refer to this account in other API calls.")
  public UUID getId() {
    return id;
  }
  
  
  /**
  * The date &amp; time at which the account object was created.
  * @return created
  **/
  @ApiModelProperty(value = "The date & time at which the account object was created.")
  public OffsetDateTime getCreated() {
    return created;
  }
  
  
  /**
  * The date &amp; time at which the account object was last accessed.
  * @return lastAccessed
  **/
  @ApiModelProperty(value = "The date & time at which the account object was last accessed.")
  public OffsetDateTime getLastAccessed() {
    return lastAccessed;
  }
  
  
  /**
  * The Account IBAN
  * @return iban
  **/
  @ApiModelProperty(value = "The Account IBAN")
  public String getIban() {
    return iban;
  }
  
  
  /**
  * The ASPSP associated with this account.
  * @return institutionId
  **/
  @ApiModelProperty(value = "The ASPSP associated with this account.")
  public String getInstitutionId() {
    return institutionId;
  }
  
  
  /**
  * The processing status of this account.
  * @return status
  **/
  @ApiModelProperty(value = "The processing status of this account.")
  public Object getStatus() {
    return status;
  }
  
  
  /**
  * The name of the account owner.
  * @return ownerName
  **/
  @ApiModelProperty(value = "The name of the account owner.")
  public String getOwnerName() {
    return ownerName;
  }
  
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AccountV2 accountV2 = (AccountV2) o;
    return Objects.equals(this.id, accountV2.id) &&
        Objects.equals(this.created, accountV2.created) &&
        Objects.equals(this.lastAccessed, accountV2.lastAccessed) &&
        Objects.equals(this.iban, accountV2.iban) &&
        Objects.equals(this.institutionId, accountV2.institutionId) &&
        Objects.equals(this.status, accountV2.status) &&
        Objects.equals(this.ownerName, accountV2.ownerName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, created, lastAccessed, iban, institutionId, status, ownerName);
  }
  
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountV2 {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    lastAccessed: ").append(toIndentedString(lastAccessed)).append("\n");
    sb.append("    iban: ").append(toIndentedString(iban)).append("\n");
    sb.append("    institutionId: ").append(toIndentedString(institutionId)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    ownerName: ").append(toIndentedString(ownerName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  
}



