/*
 * Nordigen Account Information Services API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0 (v2)
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package nordigen;



import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;



/**
 * Gets or Sets CountryEnum
 */

public enum CountryEnum {
  
  AT("AT"),
  
  BE("BE"),
  
  BG("BG"),
  
  HR("HR"),
  
  CY("CY"),
  
  CZ("CZ"),
  
  DK("DK"),
  
  EE("EE"),
  
  FI("FI"),
  
  FR("FR"),
  
  DE("DE"),
  
  GR("GR"),
  
  HU("HU"),
  
  IS("IS"),
  
  IE("IE"),
  
  IT("IT"),
  
  LV("LV"),
  
  LI("LI"),
  
  LT("LT"),
  
  LU("LU"),
  
  MT("MT"),
  
  NL("NL"),
  
  NO("NO"),
  
  PL("PL"),
  
  PT("PT"),
  
  RO("RO"),
  
  SK("SK"),
  
  SI("SI"),
  
  ES("ES"),
  
  SE("SE"),
  
  GB("GB");

  private String value;

  CountryEnum(String value) {
    this.value = value;
  }


  @JsonValue

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }


  @JsonCreator

  public static CountryEnum fromValue(String text) {
    for (CountryEnum b : CountryEnum.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

}



