/*
 * Nordigen Account Information Services API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0 (v2)
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package nordigen;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;
import java.util.UUID;

/**
 * Creditor account read serializer.
 */@ApiModel(description = "Creditor account read serializer.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2023-02-25T17:56:18.166387600+01:00[Europe/Warsaw]")
public class CreditorAccount {

  
  @JsonProperty("id")
  private UUID id = null;
  
  
  @JsonProperty("name")
  private String name = null;
  
  
  @JsonProperty("type")
  private Object type;
  
  
  @JsonProperty("account")
  private String account = null;
  
  
  @JsonProperty("currency")
  private String currency = null;
  
  
  @JsonProperty("address_country")
  private String addressCountry = null;
  
  
  /**
  * Unique entry ID
  * @return id
  **/
  @ApiModelProperty(value = "Unique entry ID")
  public UUID getId() {
    return id;
  }
  
  public CreditorAccount name(String name) {
    this.name = name;
    return this;
  }

  
  /**
  * Creditor account name
  * @return name
  **/
  @ApiModelProperty(required = true, value = "Creditor account name")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }
  
  public CreditorAccount type(Object type) {
    this.type = type;
    return this;
  }

  
  /**
  * Creditor account type
  * @return type
  **/
  @ApiModelProperty(value = "Creditor account type")
  public Object getType() {
    return type;
  }
  public void setType(Object type) {
    this.type = type;
  }
  
  public CreditorAccount account(String account) {
    this.account = account;
    return this;
  }

  
  /**
  * Creditor account type identifier
  * @return account
  **/
  @ApiModelProperty(required = true, value = "Creditor account type identifier")
  public String getAccount() {
    return account;
  }
  public void setAccount(String account) {
    this.account = account;
  }
  
  public CreditorAccount currency(String currency) {
    this.currency = currency;
    return this;
  }

  
  /**
  * Creditor account currency
  * @return currency
  **/
  @ApiModelProperty(required = true, value = "Creditor account currency")
  public String getCurrency() {
    return currency;
  }
  public void setCurrency(String currency) {
    this.currency = currency;
  }
  
  public CreditorAccount addressCountry(String addressCountry) {
    this.addressCountry = addressCountry;
    return this;
  }

  
  /**
  * Creditor account address country
  * @return addressCountry
  **/
  @ApiModelProperty(value = "Creditor account address country")
  public String getAddressCountry() {
    return addressCountry;
  }
  public void setAddressCountry(String addressCountry) {
    this.addressCountry = addressCountry;
  }
  
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreditorAccount creditorAccount = (CreditorAccount) o;
    return Objects.equals(this.id, creditorAccount.id) &&
        Objects.equals(this.name, creditorAccount.name) &&
        Objects.equals(this.type, creditorAccount.type) &&
        Objects.equals(this.account, creditorAccount.account) &&
        Objects.equals(this.currency, creditorAccount.currency) &&
        Objects.equals(this.addressCountry, creditorAccount.addressCountry);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, type, account, currency, addressCountry);
  }
  
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreditorAccount {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    account: ").append(toIndentedString(account)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    addressCountry: ").append(toIndentedString(addressCountry)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  
}



