/*
 * Nordigen Account Information Services API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0 (v2)
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package nordigen;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Debtor account write serializer.
 */@ApiModel(description = "Debtor account write serializer.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2023-02-25T17:56:18.166387600+01:00[Europe/Warsaw]")
public class DebtorAccountWriteRequest {

  
  @JsonProperty("currency")
  private String currency = null;
  
  
  @JsonProperty("account")
  private String account = null;
  
  
  @JsonProperty("type_number")
  private String typeNumber = null;
  
  
  @JsonProperty("type")
  private Object type;
  
  
  @JsonProperty("name")
  private String name = null;
  
  
  @JsonProperty("address_country")
  private String addressCountry = null;
  
  
  @JsonProperty("post_code")
  private String postCode = null;
  
  
  @JsonProperty("address_street")
  private String addressStreet = null;
  
  public DebtorAccountWriteRequest currency(String currency) {
    this.currency = currency;
    return this;
  }

  
  /**
  * Debtor account currency
  * @return currency
  **/
  @ApiModelProperty(value = "Debtor account currency")
  public String getCurrency() {
    return currency;
  }
  public void setCurrency(String currency) {
    this.currency = currency;
  }
  
  public DebtorAccountWriteRequest account(String account) {
    this.account = account;
    return this;
  }

  
  /**
  * Debtor account type identifier
  * @return account
  **/
  @ApiModelProperty(value = "Debtor account type identifier")
  public String getAccount() {
    return account;
  }
  public void setAccount(String account) {
    this.account = account;
  }
  
  public DebtorAccountWriteRequest typeNumber(String typeNumber) {
    this.typeNumber = typeNumber;
    return this;
  }

  
  /**
  * Debtor account type identifier
  * @return typeNumber
  **/
  @ApiModelProperty(value = "Debtor account type identifier")
  public String getTypeNumber() {
    return typeNumber;
  }
  public void setTypeNumber(String typeNumber) {
    this.typeNumber = typeNumber;
  }
  
  public DebtorAccountWriteRequest type(Object type) {
    this.type = type;
    return this;
  }

  
  /**
  * Debtor account type
  * @return type
  **/
  @ApiModelProperty(value = "Debtor account type")
  public Object getType() {
    return type;
  }
  public void setType(Object type) {
    this.type = type;
  }
  
  public DebtorAccountWriteRequest name(String name) {
    this.name = name;
    return this;
  }

  
  /**
  * Debtor account name
  * @return name
  **/
  @ApiModelProperty(required = true, value = "Debtor account name")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }
  
  public DebtorAccountWriteRequest addressCountry(String addressCountry) {
    this.addressCountry = addressCountry;
    return this;
  }

  
  /**
  * Debtor account address country
  * @return addressCountry
  **/
  @ApiModelProperty(value = "Debtor account address country")
  public String getAddressCountry() {
    return addressCountry;
  }
  public void setAddressCountry(String addressCountry) {
    this.addressCountry = addressCountry;
  }
  
  public DebtorAccountWriteRequest postCode(String postCode) {
    this.postCode = postCode;
    return this;
  }

  
  /**
  * Debtor account post code
  * @return postCode
  **/
  @ApiModelProperty(value = "Debtor account post code")
  public String getPostCode() {
    return postCode;
  }
  public void setPostCode(String postCode) {
    this.postCode = postCode;
  }
  
  public DebtorAccountWriteRequest addressStreet(String addressStreet) {
    this.addressStreet = addressStreet;
    return this;
  }

  
  /**
  * Debtor account address street
  * @return addressStreet
  **/
  @ApiModelProperty(value = "Debtor account address street")
  public String getAddressStreet() {
    return addressStreet;
  }
  public void setAddressStreet(String addressStreet) {
    this.addressStreet = addressStreet;
  }
  
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DebtorAccountWriteRequest debtorAccountWriteRequest = (DebtorAccountWriteRequest) o;
    return Objects.equals(this.currency, debtorAccountWriteRequest.currency) &&
        Objects.equals(this.account, debtorAccountWriteRequest.account) &&
        Objects.equals(this.typeNumber, debtorAccountWriteRequest.typeNumber) &&
        Objects.equals(this.type, debtorAccountWriteRequest.type) &&
        Objects.equals(this.name, debtorAccountWriteRequest.name) &&
        Objects.equals(this.addressCountry, debtorAccountWriteRequest.addressCountry) &&
        Objects.equals(this.postCode, debtorAccountWriteRequest.postCode) &&
        Objects.equals(this.addressStreet, debtorAccountWriteRequest.addressStreet);
  }

  @Override
  public int hashCode() {
    return Objects.hash(currency, account, typeNumber, type, name, addressCountry, postCode, addressStreet);
  }
  
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DebtorAccountWriteRequest {\n");
    
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    account: ").append(toIndentedString(account)).append("\n");
    sb.append("    typeNumber: ").append(toIndentedString(typeNumber)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    addressCountry: ").append(toIndentedString(addressCountry)).append("\n");
    sb.append("    postCode: ").append(toIndentedString(postCode)).append("\n");
    sb.append("    addressStreet: ").append(toIndentedString(addressStreet)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  
}



