/*
 * Nordigen Account Information Services API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0 (v2)
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package nordigen;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Represents end-user details.
 */@ApiModel(description = "Represents end-user details.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2023-02-25T17:56:18.166387600+01:00[Europe/Warsaw]")
public class EnduserAcceptanceDetailsRequest {

  
  @JsonProperty("user_agent")
  private String userAgent = null;
  
  
  @JsonProperty("ip_address")
  private String ipAddress = null;
  
  public EnduserAcceptanceDetailsRequest userAgent(String userAgent) {
    this.userAgent = userAgent;
    return this;
  }

  
  /**
  * Get userAgent
  * @return userAgent
  **/
  @ApiModelProperty(required = true, value = "")
  public String getUserAgent() {
    return userAgent;
  }
  public void setUserAgent(String userAgent) {
    this.userAgent = userAgent;
  }
  
  public EnduserAcceptanceDetailsRequest ipAddress(String ipAddress) {
    this.ipAddress = ipAddress;
    return this;
  }

  
  /**
  * Get ipAddress
  * @return ipAddress
  **/
  @ApiModelProperty(required = true, value = "")
  public String getIpAddress() {
    return ipAddress;
  }
  public void setIpAddress(String ipAddress) {
    this.ipAddress = ipAddress;
  }
  
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EnduserAcceptanceDetailsRequest enduserAcceptanceDetailsRequest = (EnduserAcceptanceDetailsRequest) o;
    return Objects.equals(this.userAgent, enduserAcceptanceDetailsRequest.userAgent) &&
        Objects.equals(this.ipAddress, enduserAcceptanceDetailsRequest.ipAddress);
  }

  @Override
  public int hashCode() {
    return Objects.hash(userAgent, ipAddress);
  }
  
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EnduserAcceptanceDetailsRequest {\n");
    
    sb.append("    userAgent: ").append(toIndentedString(userAgent)).append("\n");
    sb.append("    ipAddress: ").append(toIndentedString(ipAddress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  
}



