/*
 * Nordigen Account Information Services API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0 (v2)
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package nordigen;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * EndUserAgreement.
 */@ApiModel(description = "EndUserAgreement.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2023-02-25T17:56:18.166387600+01:00[Europe/Warsaw]")
public class EndUserAgreementRequest {

  
  @JsonProperty("max_historical_days")
  private Integer maxHistoricalDays = 90;
  
  
  @JsonProperty("access_valid_for_days")
  private Integer accessValidForDays = 90;
  
  
  @JsonProperty("access_scope")
  private List<String> accessScope = null;
  
  
  @JsonProperty("institution_id")
  private String institutionId = null;
  
  public EndUserAgreementRequest maxHistoricalDays(Integer maxHistoricalDays) {
    this.maxHistoricalDays = maxHistoricalDays;
    return this;
  }

  
  /**
  * Maximum number of days of transaction data to retrieve.
  * minimum: 1
  * maximum: 730
  * @return maxHistoricalDays
  **/
  @ApiModelProperty(value = "Maximum number of days of transaction data to retrieve.")
  public Integer getMaxHistoricalDays() {
    return maxHistoricalDays;
  }
  public void setMaxHistoricalDays(Integer maxHistoricalDays) {
    this.maxHistoricalDays = maxHistoricalDays;
  }
  
  public EndUserAgreementRequest accessValidForDays(Integer accessValidForDays) {
    this.accessValidForDays = accessValidForDays;
    return this;
  }

  
  /**
  * Number of days from acceptance that the access can be used.
  * minimum: 1
  * maximum: 90
  * @return accessValidForDays
  **/
  @ApiModelProperty(value = "Number of days from acceptance that the access can be used.")
  public Integer getAccessValidForDays() {
    return accessValidForDays;
  }
  public void setAccessValidForDays(Integer accessValidForDays) {
    this.accessValidForDays = accessValidForDays;
  }
  
  public EndUserAgreementRequest accessScope(List<String> accessScope) {
    this.accessScope = accessScope;
    return this;
  }

  public EndUserAgreementRequest addAccessScopeItem(String accessScopeItem) {
    
    if (this.accessScope == null) {
      this.accessScope = new ArrayList<String>();
    }
    
    this.accessScope.add(accessScopeItem);
    return this;
  }
  
  /**
  * Array containing one or several values of [&#x27;balances&#x27;, &#x27;details&#x27;, &#x27;transactions&#x27;]
  * @return accessScope
  **/
  @ApiModelProperty(value = "Array containing one or several values of ['balances', 'details', 'transactions']")
  public List<String> getAccessScope() {
    return accessScope;
  }
  public void setAccessScope(List<String> accessScope) {
    this.accessScope = accessScope;
  }
  
  public EndUserAgreementRequest institutionId(String institutionId) {
    this.institutionId = institutionId;
    return this;
  }

  
  /**
  * an Institution ID for this EUA
  * @return institutionId
  **/
  @ApiModelProperty(required = true, value = "an Institution ID for this EUA")
  public String getInstitutionId() {
    return institutionId;
  }
  public void setInstitutionId(String institutionId) {
    this.institutionId = institutionId;
  }
  
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EndUserAgreementRequest endUserAgreementRequest = (EndUserAgreementRequest) o;
    return Objects.equals(this.maxHistoricalDays, endUserAgreementRequest.maxHistoricalDays) &&
        Objects.equals(this.accessValidForDays, endUserAgreementRequest.accessValidForDays) &&
        Objects.equals(this.accessScope, endUserAgreementRequest.accessScope) &&
        Objects.equals(this.institutionId, endUserAgreementRequest.institutionId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(maxHistoricalDays, accessValidForDays, accessScope, institutionId);
  }
  
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EndUserAgreementRequest {\n");
    
    sb.append("    maxHistoricalDays: ").append(toIndentedString(maxHistoricalDays)).append("\n");
    sb.append("    accessValidForDays: ").append(toIndentedString(accessValidForDays)).append("\n");
    sb.append("    accessScope: ").append(toIndentedString(accessScope)).append("\n");
    sb.append("    institutionId: ").append(toIndentedString(institutionId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  
}



