/*
 * Nordigen Account Information Services API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0 (v2)
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package nordigen;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

/**
 * Represents an Integration.
 */@ApiModel(description = "Represents an Integration.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2023-02-25T17:56:18.166387600+01:00[Europe/Warsaw]")
public class Integration {

  
  @JsonProperty("id")
  private String id = null;
  
  
  @JsonProperty("name")
  private String name = null;
  
  
  @JsonProperty("bic")
  private String bic = null;
  
  
  @JsonProperty("transaction_total_days")
  private String transactionTotalDays = "90";
  
  
  @JsonProperty("countries")
  private List<String> countries = new ArrayList<String>();
  
  
  @JsonProperty("logo")
  private String logo = null;
  
  public Integration id(String id) {
    this.id = id;
    return this;
  }

  
  /**
  * Get id
  * @return id
  **/
  @ApiModelProperty(required = true, value = "")
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }
  
  public Integration name(String name) {
    this.name = name;
    return this;
  }

  
  /**
  * Get name
  * @return name
  **/
  @ApiModelProperty(required = true, value = "")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }
  
  public Integration bic(String bic) {
    this.bic = bic;
    return this;
  }

  
  /**
  * Get bic
  * @return bic
  **/
  @ApiModelProperty(value = "")
  public String getBic() {
    return bic;
  }
  public void setBic(String bic) {
    this.bic = bic;
  }
  
  public Integration transactionTotalDays(String transactionTotalDays) {
    this.transactionTotalDays = transactionTotalDays;
    return this;
  }

  
  /**
  * Get transactionTotalDays
  * @return transactionTotalDays
  **/
  @ApiModelProperty(value = "")
  public String getTransactionTotalDays() {
    return transactionTotalDays;
  }
  public void setTransactionTotalDays(String transactionTotalDays) {
    this.transactionTotalDays = transactionTotalDays;
  }
  
  public Integration countries(List<String> countries) {
    this.countries = countries;
    return this;
  }

  public Integration addCountriesItem(String countriesItem) {
    
    this.countries.add(countriesItem);
    return this;
  }
  
  /**
  * Get countries
  * @return countries
  **/
  @ApiModelProperty(required = true, value = "")
  public List<String> getCountries() {
    return countries;
  }
  public void setCountries(List<String> countries) {
    this.countries = countries;
  }
  
  public Integration logo(String logo) {
    this.logo = logo;
    return this;
  }

  
  /**
  * Get logo
  * @return logo
  **/
  @ApiModelProperty(required = true, value = "")
  public String getLogo() {
    return logo;
  }
  public void setLogo(String logo) {
    this.logo = logo;
  }
  
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Integration integration = (Integration) o;
    return Objects.equals(this.id, integration.id) &&
        Objects.equals(this.name, integration.name) &&
        Objects.equals(this.bic, integration.bic) &&
        Objects.equals(this.transactionTotalDays, integration.transactionTotalDays) &&
        Objects.equals(this.countries, integration.countries) &&
        Objects.equals(this.logo, integration.logo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, name, bic, transactionTotalDays, countries, logo);
  }
  
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Integration {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    bic: ").append(toIndentedString(bic)).append("\n");
    sb.append("    transactionTotalDays: ").append(toIndentedString(transactionTotalDays)).append("\n");
    sb.append("    countries: ").append(toIndentedString(countries)).append("\n");
    sb.append("    logo: ").append(toIndentedString(logo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  
}



