/*
 * Nordigen Account Information Services API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0 (v2)
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package nordigen;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.experimental.Accessors;

import java.util.Objects;

/**
 * Obtain JWT pair.
 */@ApiModel(description = "Obtain JWT pair.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2023-02-25T17:56:18.166387600+01:00[Europe/Warsaw]")
@Accessors(chain = true)
public class JWTObtainPairRequest {

  
  @JsonProperty("secret_id")
  private String secretId = null;
  
  
  @JsonProperty("secret_key")
  private String secretKey = null;
  
  public JWTObtainPairRequest secretId(String secretId) {
    this.secretId = secretId;
    return this;
  }

  
  /**
  * Secret id from /user-secrets/
  * @return secretId
  **/
  @ApiModelProperty(required = true, value = "Secret id from /user-secrets/")
  public String getSecretId() {
    return secretId;
  }
  public void setSecretId(String secretId) {
    this.secretId = secretId;
  }
  
  public JWTObtainPairRequest secretKey(String secretKey) {
    this.secretKey = secretKey;
    return this;
  }

  
  /**
  * Secret key from /user-secrets/
  * @return secretKey
  **/
  @ApiModelProperty(required = true, value = "Secret key from /user-secrets/")
  public String getSecretKey() {
    return secretKey;
  }
  public void setSecretKey(String secretKey) {
    this.secretKey = secretKey;
  }
  
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JWTObtainPairRequest jwTObtainPairRequest = (JWTObtainPairRequest) o;
    return Objects.equals(this.secretId, jwTObtainPairRequest.secretId) &&
        Objects.equals(this.secretKey, jwTObtainPairRequest.secretKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(secretId, secretKey);
  }
  
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JWTObtainPairRequest {\n");
    
    sb.append("    secretId: ").append(toIndentedString(secretId)).append("\n");
    sb.append("    secretKey: ").append(toIndentedString(secretKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  
}



