/*
 * Nordigen Account Information Services API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0 (v2)
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package nordigen;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.time.LocalDate;
import java.util.Objects;
import java.util.UUID;

/**
 * PaymentWriteSerializer.
 */@ApiModel(description = "PaymentWriteSerializer.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2023-02-25T17:56:18.166387600+01:00[Europe/Warsaw]")
public class PaymentWrite {

  
  @JsonProperty("link")
  private String link = "https://ob.nordigen.com/pis/start/ab483032-8ac1-493b-8f33-d12f12ad45cf/{$INSTITUTION_ID}";
  
  
  @JsonProperty("payment_id")
  private String paymentId = null;
  
  
  @JsonProperty("payment_status")
  private Object paymentStatus = null;
  
  
  @JsonProperty("payment_product")
  private Object paymentProduct;
  
  
  @JsonProperty("payment_type")
  private Object paymentType = null;
  
  
  @JsonProperty("instructed_amount")
  private Object instructedAmount = null;
  
  
  @JsonProperty("creditor_account")
  private UUID creditorAccount = null;
  
  
  @JsonProperty("redirect")
  private String redirect = null;
  
  
  @JsonProperty("description")
  private String description = "GOCARDLESS";
  
  
  @JsonProperty("custom_payment_id")
  private String customPaymentId = null;
  
  
  @JsonProperty("requested_execution_date")
  private LocalDate requestedExecutionDate = null;
  
  
  @JsonProperty("periodic_payment")
  private PeriodicPayment periodicPayment = null;
  
  
  /**
  * Link to initiate authorization with Institution
  * @return link
  **/
  @ApiModelProperty(value = "Link to initiate authorization with Institution")
  public String getLink() {
    return link;
  }
  
  
  /**
  * Payment ID
  * @return paymentId
  **/
  @ApiModelProperty(value = "Payment ID")
  public String getPaymentId() {
    return paymentId;
  }
  
  
  /**
  * Payment end to end identification
  * @return paymentStatus
  **/
  @ApiModelProperty(value = "Payment end to end identification")
  public Object getPaymentStatus() {
    return paymentStatus;
  }
  
  public PaymentWrite paymentProduct(Object paymentProduct) {
    this.paymentProduct = paymentProduct;
    return this;
  }

  
  /**
  * Payment product
  * @return paymentProduct
  **/
  @ApiModelProperty(value = "Payment product")
  public Object getPaymentProduct() {
    return paymentProduct;
  }
  public void setPaymentProduct(Object paymentProduct) {
    this.paymentProduct = paymentProduct;
  }
  
  
  /**
  * Payment Type
  * @return paymentType
  **/
  @ApiModelProperty(value = "Payment Type")
  public Object getPaymentType() {
    return paymentType;
  }
  
  public PaymentWrite instructedAmount(Object instructedAmount) {
    this.instructedAmount = instructedAmount;
    return this;
  }

  
  /**
  * Instructed amount
  * @return instructedAmount
  **/
  @ApiModelProperty(required = true, value = "Instructed amount")
  public Object getInstructedAmount() {
    return instructedAmount;
  }
  public void setInstructedAmount(Object instructedAmount) {
    this.instructedAmount = instructedAmount;
  }
  
  public PaymentWrite creditorAccount(UUID creditorAccount) {
    this.creditorAccount = creditorAccount;
    return this;
  }

  
  /**
  * Registered creditor account
  * @return creditorAccount
  **/
  @ApiModelProperty(required = true, value = "Registered creditor account")
  public UUID getCreditorAccount() {
    return creditorAccount;
  }
  public void setCreditorAccount(UUID creditorAccount) {
    this.creditorAccount = creditorAccount;
  }
  
  public PaymentWrite redirect(String redirect) {
    this.redirect = redirect;
    return this;
  }

  
  /**
  * Redirect URL to your application after payment is done
  * @return redirect
  **/
  @ApiModelProperty(required = true, value = "Redirect URL to your application after payment is done")
  public String getRedirect() {
    return redirect;
  }
  public void setRedirect(String redirect) {
    this.redirect = redirect;
  }
  
  public PaymentWrite description(String description) {
    this.description = description;
    return this;
  }

  
  /**
  * Payment description
  * @return description
  **/
  @ApiModelProperty(value = "Payment description")
  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }
  
  public PaymentWrite customPaymentId(String customPaymentId) {
    this.customPaymentId = customPaymentId;
    return this;
  }

  
  /**
  * Payment Custom Payment ID
  * @return customPaymentId
  **/
  @ApiModelProperty(value = "Payment Custom Payment ID")
  public String getCustomPaymentId() {
    return customPaymentId;
  }
  public void setCustomPaymentId(String customPaymentId) {
    this.customPaymentId = customPaymentId;
  }
  
  public PaymentWrite requestedExecutionDate(LocalDate requestedExecutionDate) {
    this.requestedExecutionDate = requestedExecutionDate;
    return this;
  }

  
  /**
  * Payment Execution date (for periodic payments)
  * @return requestedExecutionDate
  **/
  @ApiModelProperty(value = "Payment Execution date (for periodic payments)")
  public LocalDate getRequestedExecutionDate() {
    return requestedExecutionDate;
  }
  public void setRequestedExecutionDate(LocalDate requestedExecutionDate) {
    this.requestedExecutionDate = requestedExecutionDate;
  }
  
  public PaymentWrite periodicPayment(PeriodicPayment periodicPayment) {
    this.periodicPayment = periodicPayment;
    return this;
  }

  
  /**
  * Get periodicPayment
  * @return periodicPayment
  **/
  @ApiModelProperty(value = "")
  public PeriodicPayment getPeriodicPayment() {
    return periodicPayment;
  }
  public void setPeriodicPayment(PeriodicPayment periodicPayment) {
    this.periodicPayment = periodicPayment;
  }
  
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentWrite paymentWrite = (PaymentWrite) o;
    return Objects.equals(this.link, paymentWrite.link) &&
        Objects.equals(this.paymentId, paymentWrite.paymentId) &&
        Objects.equals(this.paymentStatus, paymentWrite.paymentStatus) &&
        Objects.equals(this.paymentProduct, paymentWrite.paymentProduct) &&
        Objects.equals(this.paymentType, paymentWrite.paymentType) &&
        Objects.equals(this.instructedAmount, paymentWrite.instructedAmount) &&
        Objects.equals(this.creditorAccount, paymentWrite.creditorAccount) &&
        Objects.equals(this.redirect, paymentWrite.redirect) &&
        Objects.equals(this.description, paymentWrite.description) &&
        Objects.equals(this.customPaymentId, paymentWrite.customPaymentId) &&
        Objects.equals(this.requestedExecutionDate, paymentWrite.requestedExecutionDate) &&
        Objects.equals(this.periodicPayment, paymentWrite.periodicPayment);
  }

  @Override
  public int hashCode() {
    return Objects.hash(link, paymentId, paymentStatus, paymentProduct, paymentType, instructedAmount, creditorAccount, redirect, description, customPaymentId, requestedExecutionDate, periodicPayment);
  }
  
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentWrite {\n");
    
    sb.append("    link: ").append(toIndentedString(link)).append("\n");
    sb.append("    paymentId: ").append(toIndentedString(paymentId)).append("\n");
    sb.append("    paymentStatus: ").append(toIndentedString(paymentStatus)).append("\n");
    sb.append("    paymentProduct: ").append(toIndentedString(paymentProduct)).append("\n");
    sb.append("    paymentType: ").append(toIndentedString(paymentType)).append("\n");
    sb.append("    instructedAmount: ").append(toIndentedString(instructedAmount)).append("\n");
    sb.append("    creditorAccount: ").append(toIndentedString(creditorAccount)).append("\n");
    sb.append("    redirect: ").append(toIndentedString(redirect)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    customPaymentId: ").append(toIndentedString(customPaymentId)).append("\n");
    sb.append("    requestedExecutionDate: ").append(toIndentedString(requestedExecutionDate)).append("\n");
    sb.append("    periodicPayment: ").append(toIndentedString(periodicPayment)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  
}



