/*
 * Nordigen Account Information Services API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0 (v2)
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package nordigen;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;
import java.util.UUID;

/**
 * PaymentReadSerializer.
 */@ApiModel(description = "PaymentReadSerializer.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2023-02-25T17:56:18.166387600+01:00[Europe/Warsaw]")
public class PaymentRead {

  
  @JsonProperty("payment_id")
  private String paymentId = null;
  
  
  @JsonProperty("payment_status")
  private Object paymentStatus = null;
  
  
  @JsonProperty("payment_product")
  private Object paymentProduct;
  
  
  @JsonProperty("payment_type")
  private Object paymentType = null;
  
  
  @JsonProperty("redirect")
  private String redirect = null;
  
  
  @JsonProperty("description")
  private String description = "GOCARDLESS";
  
  
  @JsonProperty("custom_payment_id")
  private String customPaymentId = null;
  
  
  @JsonProperty("creditor_account")
  private UUID creditorAccount = null;
  
  
  @JsonProperty("debtor_account")
  private DebtorAccountWrite debtorAccount = null;
  
  
  @JsonProperty("instructed_amount")
  private Object instructedAmount = null;
  
  
  /**
  * Payment ID
  * @return paymentId
  **/
  @ApiModelProperty(value = "Payment ID")
  public String getPaymentId() {
    return paymentId;
  }
  
  
  /**
  * Payment end to end identification
  * @return paymentStatus
  **/
  @ApiModelProperty(value = "Payment end to end identification")
  public Object getPaymentStatus() {
    return paymentStatus;
  }
  
  public PaymentRead paymentProduct(Object paymentProduct) {
    this.paymentProduct = paymentProduct;
    return this;
  }

  
  /**
  * Payment product
  * @return paymentProduct
  **/
  @ApiModelProperty(value = "Payment product")
  public Object getPaymentProduct() {
    return paymentProduct;
  }
  public void setPaymentProduct(Object paymentProduct) {
    this.paymentProduct = paymentProduct;
  }
  
  
  /**
  * Payment Type
  * @return paymentType
  **/
  @ApiModelProperty(value = "Payment Type")
  public Object getPaymentType() {
    return paymentType;
  }
  
  public PaymentRead redirect(String redirect) {
    this.redirect = redirect;
    return this;
  }

  
  /**
  * Redirect URL to your application after payment is done
  * @return redirect
  **/
  @ApiModelProperty(required = true, value = "Redirect URL to your application after payment is done")
  public String getRedirect() {
    return redirect;
  }
  public void setRedirect(String redirect) {
    this.redirect = redirect;
  }
  
  public PaymentRead description(String description) {
    this.description = description;
    return this;
  }

  
  /**
  * Payment description
  * @return description
  **/
  @ApiModelProperty(value = "Payment description")
  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }
  
  public PaymentRead customPaymentId(String customPaymentId) {
    this.customPaymentId = customPaymentId;
    return this;
  }

  
  /**
  * Payment Custom Payment ID
  * @return customPaymentId
  **/
  @ApiModelProperty(value = "Payment Custom Payment ID")
  public String getCustomPaymentId() {
    return customPaymentId;
  }
  public void setCustomPaymentId(String customPaymentId) {
    this.customPaymentId = customPaymentId;
  }
  
  public PaymentRead creditorAccount(UUID creditorAccount) {
    this.creditorAccount = creditorAccount;
    return this;
  }

  
  /**
  * Registered creditor account
  * @return creditorAccount
  **/
  @ApiModelProperty(required = true, value = "Registered creditor account")
  public UUID getCreditorAccount() {
    return creditorAccount;
  }
  public void setCreditorAccount(UUID creditorAccount) {
    this.creditorAccount = creditorAccount;
  }
  
  public PaymentRead debtorAccount(DebtorAccountWrite debtorAccount) {
    this.debtorAccount = debtorAccount;
    return this;
  }

  
  /**
  * Get debtorAccount
  * @return debtorAccount
  **/
  @ApiModelProperty(required = true, value = "")
  public DebtorAccountWrite getDebtorAccount() {
    return debtorAccount;
  }
  public void setDebtorAccount(DebtorAccountWrite debtorAccount) {
    this.debtorAccount = debtorAccount;
  }
  
  public PaymentRead instructedAmount(Object instructedAmount) {
    this.instructedAmount = instructedAmount;
    return this;
  }

  
  /**
  * Instructed amount
  * @return instructedAmount
  **/
  @ApiModelProperty(required = true, value = "Instructed amount")
  public Object getInstructedAmount() {
    return instructedAmount;
  }
  public void setInstructedAmount(Object instructedAmount) {
    this.instructedAmount = instructedAmount;
  }
  
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentRead paymentRead = (PaymentRead) o;
    return Objects.equals(this.paymentId, paymentRead.paymentId) &&
        Objects.equals(this.paymentStatus, paymentRead.paymentStatus) &&
        Objects.equals(this.paymentProduct, paymentRead.paymentProduct) &&
        Objects.equals(this.paymentType, paymentRead.paymentType) &&
        Objects.equals(this.redirect, paymentRead.redirect) &&
        Objects.equals(this.description, paymentRead.description) &&
        Objects.equals(this.customPaymentId, paymentRead.customPaymentId) &&
        Objects.equals(this.creditorAccount, paymentRead.creditorAccount) &&
        Objects.equals(this.debtorAccount, paymentRead.debtorAccount) &&
        Objects.equals(this.instructedAmount, paymentRead.instructedAmount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(paymentId, paymentStatus, paymentProduct, paymentType, redirect, description, customPaymentId, creditorAccount, debtorAccount, instructedAmount);
  }
  
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentRead {\n");
    
    sb.append("    paymentId: ").append(toIndentedString(paymentId)).append("\n");
    sb.append("    paymentStatus: ").append(toIndentedString(paymentStatus)).append("\n");
    sb.append("    paymentProduct: ").append(toIndentedString(paymentProduct)).append("\n");
    sb.append("    paymentType: ").append(toIndentedString(paymentType)).append("\n");
    sb.append("    redirect: ").append(toIndentedString(redirect)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    customPaymentId: ").append(toIndentedString(customPaymentId)).append("\n");
    sb.append("    creditorAccount: ").append(toIndentedString(creditorAccount)).append("\n");
    sb.append("    debtorAccount: ").append(toIndentedString(debtorAccount)).append("\n");
    sb.append("    instructedAmount: ").append(toIndentedString(instructedAmount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  
}



