/*
 * Nordigen Account Information Services API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0 (v2)
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package nordigen;



import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;



/**
 * Gets or Sets PaymentTypeEnum
 */

public enum PaymentTypeEnum {
  
  SINGLE_PAYMENT("single-payment"),
  
  BULK_PAYMENT("bulk-payment"),
  
  PERIODIC_PAYMENT("periodic-payment");

  private String value;

  PaymentTypeEnum(String value) {
    this.value = value;
  }


  @JsonValue

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }


  @JsonCreator

  public static PaymentTypeEnum fromValue(String text) {
    for (PaymentTypeEnum b : PaymentTypeEnum.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

}



