/*
 * Nordigen Account Information Services API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0 (v2)
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package nordigen;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.time.LocalDate;
import java.util.Objects;

/**
 * Periodic Payment Serializer.
 */@ApiModel(description = "Periodic Payment Serializer.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2023-02-25T17:56:18.166387600+01:00[Europe/Warsaw]")
public class PeriodicPayment {

  
  @JsonProperty("frequency")
  private Object frequency ;
  
  
  @JsonProperty("start_date")
  private LocalDate startDate = null;
  
  
  @JsonProperty("end_date")
  private LocalDate endDate = null;
  
  
  @JsonProperty("execution_rule")
  private Object executionRule;
  
  
  @JsonProperty("day_of_execution")
  private String dayOfExecution = null;
  
  public PeriodicPayment frequency(Object frequency) {
    this.frequency = frequency;
    return this;
  }

  
  /**
  * Get frequency
  * @return frequency
  **/
  @ApiModelProperty(value = "")
  public Object getFrequency() {
    return frequency;
  }
  public void setFrequency(Object frequency) {
    this.frequency = frequency;
  }
  
  public PeriodicPayment startDate(LocalDate startDate) {
    this.startDate = startDate;
    return this;
  }

  
  /**
  * Get startDate
  * @return startDate
  **/
  @ApiModelProperty(required = true, value = "")
  public LocalDate getStartDate() {
    return startDate;
  }
  public void setStartDate(LocalDate startDate) {
    this.startDate = startDate;
  }
  
  public PeriodicPayment endDate(LocalDate endDate) {
    this.endDate = endDate;
    return this;
  }

  
  /**
  * Get endDate
  * @return endDate
  **/
  @ApiModelProperty(value = "")
  public LocalDate getEndDate() {
    return endDate;
  }
  public void setEndDate(LocalDate endDate) {
    this.endDate = endDate;
  }
  
  public PeriodicPayment executionRule(Object executionRule) {
    this.executionRule = executionRule;
    return this;
  }

  
  /**
  * Behavior when periodic payment dates fall on holiday.
  * @return executionRule
  **/
  @ApiModelProperty(value = "Behavior when periodic payment dates fall on holiday.")
  public Object getExecutionRule() {
    return executionRule;
  }
  public void setExecutionRule(Object executionRule) {
    this.executionRule = executionRule;
  }
  
  public PeriodicPayment dayOfExecution(String dayOfExecution) {
    this.dayOfExecution = dayOfExecution;
    return this;
  }

  
  /**
  * Get dayOfExecution
  * @return dayOfExecution
  **/
  @ApiModelProperty(value = "")
  public String getDayOfExecution() {
    return dayOfExecution;
  }
  public void setDayOfExecution(String dayOfExecution) {
    this.dayOfExecution = dayOfExecution;
  }
  
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PeriodicPayment periodicPayment = (PeriodicPayment) o;
    return Objects.equals(this.frequency, periodicPayment.frequency) &&
        Objects.equals(this.startDate, periodicPayment.startDate) &&
        Objects.equals(this.endDate, periodicPayment.endDate) &&
        Objects.equals(this.executionRule, periodicPayment.executionRule) &&
        Objects.equals(this.dayOfExecution, periodicPayment.dayOfExecution);
  }

  @Override
  public int hashCode() {
    return Objects.hash(frequency, startDate, endDate, executionRule, dayOfExecution);
  }
  
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PeriodicPayment {\n");
    
    sb.append("    frequency: ").append(toIndentedString(frequency)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    executionRule: ").append(toIndentedString(executionRule)).append("\n");
    sb.append("    dayOfExecution: ").append(toIndentedString(dayOfExecution)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  
}



