/*
 * Nordigen Account Information Services API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0 (v2)
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package nordigen;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.time.LocalDate;
import java.util.Objects;

/**
 * Filter country.
 */@ApiModel(description = "Filter country.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2023-02-25T17:56:18.166387600+01:00[Europe/Warsaw]")
public class PremiumAccountQuery {

  
  @JsonProperty("date_from")
  private LocalDate dateFrom = null;
  
  
  @JsonProperty("date_to")
  private LocalDate dateTo = null;
  
  
  @JsonProperty("country")
  private CountryEnum country = null;
  
  public PremiumAccountQuery dateFrom(LocalDate dateFrom) {
    this.dateFrom = dateFrom;
    return this;
  }

  
  /**
  * Get dateFrom
  * @return dateFrom
  **/
  @ApiModelProperty(value = "")
  public LocalDate getDateFrom() {
    return dateFrom;
  }
  public void setDateFrom(LocalDate dateFrom) {
    this.dateFrom = dateFrom;
  }
  
  public PremiumAccountQuery dateTo(LocalDate dateTo) {
    this.dateTo = dateTo;
    return this;
  }

  
  /**
  * Get dateTo
  * @return dateTo
  **/
  @ApiModelProperty(value = "")
  public LocalDate getDateTo() {
    return dateTo;
  }
  public void setDateTo(LocalDate dateTo) {
    this.dateTo = dateTo;
  }
  
  public PremiumAccountQuery country(CountryEnum country) {
    this.country = country;
    return this;
  }

  
  /**
  * Get country
  * @return country
  **/
  @ApiModelProperty(value = "")
  public CountryEnum getCountry() {
    return country;
  }
  public void setCountry(CountryEnum country) {
    this.country = country;
  }
  
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PremiumAccountQuery premiumAccountQuery = (PremiumAccountQuery) o;
    return Objects.equals(this.dateFrom, premiumAccountQuery.dateFrom) &&
        Objects.equals(this.dateTo, premiumAccountQuery.dateTo) &&
        Objects.equals(this.country, premiumAccountQuery.country);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dateFrom, dateTo, country);
  }
  
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PremiumAccountQuery {\n");
    
    sb.append("    dateFrom: ").append(toIndentedString(dateFrom)).append("\n");
    sb.append("    dateTo: ").append(toIndentedString(dateTo)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  
}



