/*
 * Nordigen Account Information Services API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0 (v2)
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package nordigen;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * Obtain new JWT pair.
 */@ApiModel(description = "Obtain new JWT pair.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.java.JavaClientCodegen", date = "2023-02-25T17:56:18.166387600+01:00[Europe/Warsaw]")
public class SpectacularJWTObtain {

  
  @JsonProperty("access")
  private String access = null;
  
  
  @JsonProperty("access_expires")
  private Integer accessExpires = 86400;
  
  
  @JsonProperty("refresh")
  private String refresh = null;
  
  
  @JsonProperty("refresh_expires")
  private Integer refreshExpires = 2592000;
  
  
  /**
  * Your access token
  * @return access
  **/
  @ApiModelProperty(value = "Your access token")
  public String getAccess() {
    return access;
  }
  
  
  /**
  * Access token expires in seconds
  * @return accessExpires
  **/
  @ApiModelProperty(value = "Access token expires in seconds")
  public Integer getAccessExpires() {
    return accessExpires;
  }
  
  
  /**
  * Your refresh token
  * @return refresh
  **/
  @ApiModelProperty(value = "Your refresh token")
  public String getRefresh() {
    return refresh;
  }
  
  
  /**
  * Refresh token expires in seconds
  * @return refreshExpires
  **/
  @ApiModelProperty(value = "Refresh token expires in seconds")
  public Integer getRefreshExpires() {
    return refreshExpires;
  }
  
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SpectacularJWTObtain spectacularJWTObtain = (SpectacularJWTObtain) o;
    return Objects.equals(this.access, spectacularJWTObtain.access) &&
        Objects.equals(this.accessExpires, spectacularJWTObtain.accessExpires) &&
        Objects.equals(this.refresh, spectacularJWTObtain.refresh) &&
        Objects.equals(this.refreshExpires, spectacularJWTObtain.refreshExpires);
  }

  @Override
  public int hashCode() {
    return Objects.hash(access, accessExpires, refresh, refreshExpires);
  }
  
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SpectacularJWTObtain {\n");
    
    sb.append("    access: ").append(toIndentedString(access)).append("\n");
    sb.append("    accessExpires: ").append(toIndentedString(accessExpires)).append("\n");
    sb.append("    refresh: ").append(toIndentedString(refresh)).append("\n");
    sb.append("    refreshExpires: ").append(toIndentedString(refreshExpires)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  
}



