/*
 * Nordigen Account Information Services API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0 (v2)
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package nordigen;



import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;



/**
 * Gets or Sets Status1c5Enum
 */

public enum Status1c5Enum {
  
  CR("CR"),
  
  ID("ID"),
  
  LN("LN"),
  
  RJ("RJ"),
  
  ER("ER"),
  
  SU("SU"),
  
  EX("EX"),
  
  GC("GC"),
  
  UA("UA"),
  
  GA("GA"),
  
  SA("SA");

  private String value;

  Status1c5Enum(String value) {
    this.value = value;
  }


  @JsonValue

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }


  @JsonCreator

  public static Status1c5Enum fromValue(String text) {
    for (Status1c5Enum b : Status1c5Enum.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

}



