openapi: 3.1.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /api/create_link_token:
    get:
      summary: Returns curent version of backend
      description: Optional extended description in CommonMark or HTML.
      tags:
        - createLinkToken
      responses:
        '200':    # status code
          description: Plaid Link Token
          content:
            application/json:
              schema:
                type: plaidToken
components:
  schemas:
    plaidToken:
      type: object
      required:  
        - value
      properties:
        value:
          type: string
          example: 4
