openapi: 3.1.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /api/create_link_token:
    get:
      summary: Returns curent version of backend
      description: Optional extended description in CommonMark or HTML.
      tags:
        - CreateLinkToken
      operationId: createLinkToken
      responses:
        '200':    # status code
          description: Plaid Link Token
          content:
            application/json:
              schema:
                type: LinkToken

  /api/exchange_public_token:
    post:
      description: converts public token -> access token
      tags:
        - ExchangeLinkToken
      operationId: exchangeLinkToken
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: PublicToken
      responses:
        '200':
          description: public token to be used to get bank data
          content:
            application/json:
              schema:
                type: AccessToken

  /api/transactions:
    post:
      description: list of transactions
      tags:
        - Transactions
      operationId: transactions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: AccessToken
      responses:
        '200':
          description: List of transactions
          content:
            application/json:
              schema:
                type: array
                items:
                  type: TransactionDTO


components:
  schemas:

    LinkToken:
      type: object
      required:  
        - linkToken
      properties:
        linkToken:
          type: string
          example: 

    PublicToken:
      type: object
      required:  
        - publicToken
      properties:
        publicToken:
          type: string
          example: 

    AccessToken:
      type: object
      required:  
        - acecssToken
      properties:
        accessToken:
          type: string
          example: 

    TransactionDTO:
      type: object
      required: [id, amount]
      properties:
        id:
          type: string 
        amount:
          type: double
