# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: uservice-webapi build and test

on:
  push:
    branches:
      - siudeks/issue49
    paths: 
      - .github/workflows/uservice-webapi-build.yaml
      - uservice-webapi/**
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - siudeks/issue49
    paths:
      - .github/workflows/uservice-webapi-build.yaml
      - uservice-webapi/**

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev01
    env:
      FIN2SET_CLIENT_ID: ${{ secrets.FIN2SET_CLIENT_ID }}
      FIN2SET_CLIENT_SECRET: ${{ secrets.FIN2SET_CLIENT_SECRET }}

    steps:

      - uses: actions/checkout@v3

      - name: Set SEMVERSION
        run: echo "SEMVERSION=$(cat .semversion)" >> $GITHUB_ENV
        working-directory: uservice-webapi

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: 21
          # https://github.com/actions/setup-java#supported-distributions
          distribution: temurin
          cache: maven

      - name: Build with Maven
        run: mvn -B --no-transfer-progress package -Drevision=$SEMVERSION
        working-directory: uservice-webapi
